/* Automatically generated by './build/bin/build-entry.js' */

import Input from '../packages/input/index.js';
import Card from '../packages/card/index.js';
import Link from '../packages/link/index.js';

const components = [
  Input,
  Card,
  Link
]

const install = function(Vue) {

  components.forEach(component => {
    Vue.component(component.name, component);
  })

}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.1',
  install,
  Input,
  Card,
  Link
}
